language: python
python:
  - "3.8"

# command to install dependencies
install:
  # Install autoreduction
  - git reset --soft HEAD^
  # Install autoreduction
  - pip install -r requirements.txt
script:
  - py.test --cov=system_monitoring

