language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  # Install autoreduction
  - git reset --soft HEAD^
  # Install autoreduction
  - pip install -r requirements.txt

script:
  # ================ Functional tests =============== #
  - echo "Running Unit tests"
  - py.test --cov=system_monitoring

after_success:
  - coveralls