language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  
# command to install dependencies
install:
  # Install autoreduction monitor
  - pip install -e .
  # Install test suite dependencies
  - pip install -r requirements.txt
  
# command to run tests
script: pytest
  
after_success:
  - coveralls
