language: python
python:
  - "3.8"

# command to install dependencies
install:
  # Install autoreduction
  - pip3 install -e .
  # Install autoreduction
  - pip3 install -r requirements.txt

script:
  # ================ Functional tests =============== #
  - echo "Running Unit tests"
  - py.test --cov=system_monitoring

